language: minimal
matrix:
  include:
    - dist: xenial
      script:
        - bash -c 'echo NO-OP'

deploy:
  - provider: launchpad
    slug: "~hxr-io/turtlebot-loadout-base/+git/xenial"
    oauth_token:
      secure: "Au2efaZ5byv33cxoplXtGpI5XPapEK5f7QzJ94QZKq+m22Xen34cFQlRVDJ9ajwS/SnBEIcSGIGK0Rme6eBTCsfjc1pom9eVcuM2rcor6NYdocacTW/pwUBUEvqNoqz7gB6rUFuzgpNeGIYO5lIsRwM4EYyFRBYGfDnqZ8Ts4oNDn7iKiHuQHl4OEgZ+qePvHpvz2+FArrZaUJdXz86uVbTzVwwknSXRgFkg08cL0kI/Htu7M8lKsz1gCW7LQmEyh722V+YKzZF4BAiuxtJb8W6/m4H1EnjUISi9r+nXZC9CwXLCLyit/F/+S8ArtXCHBmiIVbEYimFFoNZd2BX5SyxAlnOZzACIXr2ildW/2gfeho20Tf5jkXIbkvSsfoOSN+a+w26zlxaA6unHyIoulP5zENJNoyGMj7WAsyLGP4N09e6VPt9DdnZABpzv3gY81UXlRx5tehzBMmoPHd3aqmeGV6uuf53FzSxTnehcVnErVHs9r/Z6dO0PCfCM74apQJTcUK7DQKoHKogOkJ6gRDizkOovQJW/f8uIf8rvtC3hWzxB/06lUF0f7pzPmrf1pHZbuEamXJ62J2OYVQotGUD1ZAODz90uIpmq63Papm58AR8Ja6xIsVBldI8hLgD8m77rzfz298qNMJD3MEy/GQ86DxS2grRARJynPLbXPzw="
    oauth_token_secret:
      secure: "nM/DGJVHAT/vI9U2fvKPQHqnkwAKnBkj+HCdYGzbXPAxFv0xUxpFikH5gYR7olAPWVehmc7vsUNMqxQ24+7KJTg5HTXN16KFmRIdXcC7gkz5vtLHNycKwqc1+wa6Nlv1qzuI1bO3NI6RuLmSNsITsA/3sh0/k3yBo0CZMIOAqcK8Z7qQk1UcI8G/UnQYojWK8zuxy7+FFhD6tbcpHSao8s8qzCLaA2vyJpyJfOukcGV+EQh/xPRNKmGmSpSSZA5Dv5nSgRzngDUbF6e0aAxvZ4gYsme3PvjIB17AdH4QHSY8xvGG3WCZx3Qv1Uc45DBktm17Rh2xXIQ8j8hVGeASsBGO//MRSzgQKPNde1Q1qwFkDdbkIWKNGkLVUpIBJdaN7Z+dRvoR2QHMTMXNQ3Y/mPOFXom5SNaMxfpfSpFaszcw+X+B8lcYthHC6ruva5bbl2vi4lIhkrXDX8jCEZi1Mzc1q2v/gkjEByNbh8feiS1QdUsAip1GT4/i+kJK6tJy/Ok0Rs/8mTUpaVgPTlqnbpPvQH0Gv9YUGkKo591gxDycQeIJcKZN+QmI1V7z15M2s/oIGwbO5f9DNF+uyRgZ+wKkwPZ/OnFHggOvBRiOEsX2viJAPIYOlmD58LGKCDWgQgiQ5SYt4ysmQJaBOboCI/j3NdslR2E6/XqV+5axq2w="
